import { motion } from 'framer-motion';
import {
  ArrowLeft, ArrowRight, ArrowUpRight, BarChart3, Check, Cloud, FileCheck2,
  Gauge, Layers3, LockKeyhole, Network, RefreshCw, ShieldCheck,
  UsersRound, Workflow,
} from 'lucide-react';

const Reveal = ({ children, className = '', delay = 0 }) => (
  <motion.div initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-70px' }} transition={{ duration: 0.55, delay }} className={className}>{children}</motion.div>
);

function BackButton({ onClick, dark = false }) {
  return <button onClick={onClick} className={`inline-flex items-center gap-2 text-sm font-medium transition-colors ${dark ? 'text-white/65 hover:text-white' : 'text-slate-500 hover:text-[#000741]'}`}><ArrowLeft className="h-4 w-4" /> Back to all services</button>;
}

function Action({ children, onClick, white = false }) {
  return <button onClick={onClick} className={`inline-flex items-center gap-2 rounded-full px-6 py-3.5 text-sm font-semibold shadow-lg transition-transform hover:-translate-y-0.5 ${white ? 'bg-white text-[#000741]' : 'bg-[#000741] text-white'}`}>{children}<ArrowRight className="h-4 w-4" /></button>;
}

function Eyebrow({ children, light = false }) {
  return <p className={`text-xs font-bold uppercase tracking-[.23em] ${light ? 'text-[#4FA6FF]' : 'text-[#087fd1]'}`}>{children}</p>;
}

function GRCLayoutPro({ service, onServices, onHome }) {
  const focus = [
    ['Governance', 'Decision rights, policies, committee rhythms, and accountable ownership that make governance useful to leadership.'],
    ['Risk', 'A business-led view of technology, supplier, privacy, and operational risks so attention goes to what matters most.'],
    ['Controls', 'Practical controls, evidence routines, testing, and remediation that people can understand and sustain.'],
  ];
  const deliverables = [
    ['GRC operating model', 'Roles, escalation paths, reporting cadence, and a clear governance charter.'],
    ['Risk register and treatment plan', 'A living view of priorities, owners, actions, appetite, and residual risk.'],
    ['Control library', 'Controls mapped to obligations, systems, evidence, and responsible teams.'],
    ['Policy suite', 'Readable policies and standards built to guide everyday decisions.'],
    ['Audit readiness pack', 'Evidence plans, testing support, and clear responses to auditor requests.'],
    ['Executive reporting', 'Concise insight for leaders that connects risk with business impact.'],
  ];
  return <div className="service-detail-page min-h-screen bg-[#f5f8fc] text-[#000741]">
    <header className="relative overflow-hidden bg-[#eaf5ff] px-6 pb-20 pt-32 lg:pb-28">
      <div className="absolute inset-x-0 bottom-0 h-1 bg-[#087fd1]" />
      <div className="relative mx-auto max-w-7xl"><BackButton onClick={onServices} />
        <div className="mt-16 grid gap-12 lg:grid-cols-[.95fr_1.05fr] lg:items-center">
          <motion.div initial={{ opacity: 0, x: -22 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .7 }}>
            <Eyebrow>GRC and compliance</Eyebrow>
            <h1 className="mt-6 max-w-2xl text-5xl font-light leading-[1.02] sm:text-6xl">Clarity for the people who carry <span className="text-[#087fd1]">the accountability.</span></h1>
            <p className="mt-7 max-w-xl text-lg leading-relaxed text-slate-600">A practical GRC service for leaders who need clear ownership, meaningful risk insight, strong controls, and audit confidence without unnecessary complexity.</p>
          </motion.div>
          <Reveal className="relative min-h-[360px] overflow-hidden rounded-[32px] bg-[#087fd1] p-7 text-white sm:p-10">
            <div className="absolute right-0 top-0 h-36 w-36 rounded-bl-[72px] bg-[#4FA6FF]" />
            <div className="relative flex h-full flex-col"><div className="flex items-center justify-between"><span className="rounded-full bg-white/15 px-3 py-1.5 text-xs font-semibold">Executive view</span><FileCheck2 className="h-6 w-6" /></div><div className="mt-auto"><p className="max-w-sm text-3xl font-light leading-tight">A GRC program that helps your business move with control.</p><div className="mt-8 grid grid-cols-3 gap-2">{['Clear ownership', 'Current evidence', 'Informed decisions'].map(x => <div key={x} className="rounded-xl bg-[#000741] p-4 text-sm font-medium">{x}</div>)}</div></div></div>
          </Reveal>
        </div>
      </div>
    </header>
    <main id="grc-approach">
      <section className="mx-auto max-w-7xl px-6 py-24 lg:py-32">
        <div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><Reveal><Eyebrow>Designed for real work</Eyebrow><h2 className="mt-5 text-4xl font-light leading-tight">A compliance program people can see, understand, and use.</h2></Reveal><Reveal delay={.1}><p className="text-lg leading-relaxed text-slate-600">We turn high-level requirements into clear routines for your teams. Each part of the program is visible, owned, and connected to a decision. That means fewer unclear handoffs, more useful assurance, and a stronger foundation for growth.</p><div className="mt-8 flex flex-wrap gap-2">{['ISO aligned', 'Audit ready', 'Business led', 'Evidence based'].map(x => <span key={x} className="rounded-full bg-[#e5f3ff] px-4 py-2 text-xs font-semibold text-[#087fd1]">{x}</span>)}</div></Reveal></div>
        <div className="mt-16 grid gap-4 md:grid-cols-3">{focus.map(([title, text], i) => <Reveal key={title} delay={i * .08} className="rounded-2xl bg-white p-8 shadow-[0_10px_36px_rgba(4,7,32,.06)]"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e5f3ff] text-[#087fd1]">{i === 0 ? <Layers3 className="h-5 w-5" /> : i === 1 ? <Gauge className="h-5 w-5" /> : <ShieldCheck className="h-5 w-5" />}</div><h3 className="mt-12 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-relaxed text-slate-600">{text}</p></Reveal>)}</div>
      </section>
      <section className="bg-white px-6 py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><Eyebrow>Assurance at a glance</Eyebrow><h2 className="mt-5 text-4xl font-light">Give leaders a clear view of what is working and what needs action.</h2></div><p className="max-w-lg text-lg leading-relaxed text-slate-600">A simple assurance view replaces scattered spreadsheets and unclear status updates with an accessible, decision-ready summary.</p></div><div className="mt-14 grid gap-6 lg:grid-cols-[1.12fr_.88fr]"><div className="rounded-[28px] bg-[#000741] p-7 text-white sm:p-10"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#4FA6FF]">Program assurance summary</p><p className="mt-2 text-xl font-light">Current status across the work that matters.</p></div><span className="rounded-full bg-[#1e9a59] px-3 py-1.5 text-xs font-semibold">On track</span></div><div className="mt-10 grid gap-3 sm:grid-cols-3">{[['Controls', 'Evidence available and review dates visible.'], ['Policies', 'Owners can see what is due for review.'], ['Actions', 'Priority actions have clear accountability.']].map(([a,b]) => <div key={a} className="rounded-2xl bg-white/[.08] p-5"><Check className="h-5 w-5 text-[#4FA6FF]" /><h3 className="mt-7 font-semibold">{a}</h3><p className="mt-2 text-sm leading-relaxed text-white/60">{b}</p></div>)}</div></div><div className="grid gap-4">{[['Risk ownership', 'Each risk has a named business owner and a practical treatment plan.'], ['Control health', 'Control performance and evidence gaps can be reviewed before they become findings.'], ['Supplier exposure', 'Third parties are evaluated according to the access and impact they carry.'], ['Leadership insight', 'Decisions are supported by a concise current view, not a stack of documents.']].map(([a,b]) => <div key={a} className="rounded-2xl border border-slate-200 bg-[#f8fbff] p-5"><h3 className="font-semibold text-[#000741]">{a}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{b}</p></div>)}</div></div></div></section>
      <section className="bg-[#087fd1] px-6 py-24 text-white"><div className="mx-auto max-w-7xl"><Eyebrow light>What we deliver</Eyebrow><h2 className="mt-5 max-w-2xl text-4xl font-light">Useful artefacts, clear ownership, and a rhythm that keeps moving.</h2><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{deliverables.map(([a,b], i) => <Reveal key={a} delay={i*.05} className="rounded-2xl border border-white/20 bg-white/[.06] p-6"><FileCheck2 className="h-5 w-5 text-[#4FA6FF]" /><h3 className="mt-10 text-lg font-semibold">{a}</h3><p className="mt-3 text-sm leading-relaxed text-white/65">{b}</p></Reveal>)}</div></div></section>
      <section className="bg-[#f5f8fc] px-6 py-24"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><Eyebrow>Built around your context</Eyebrow><h2 className="mt-5 text-4xl font-light leading-tight">The right level of control for the way you work.</h2><p className="mt-6 text-lg leading-relaxed text-slate-600">We do not force a generic framework onto your organization. We tailor the operating model to your sector, size, technology environment, regulatory obligations, and appetite for risk.</p></div><div className="grid gap-4 sm:grid-cols-2">{[['Growing businesses', 'Establish the core policies, risk ownership, and governance habits needed to grow with confidence.'], ['Regulated organizations', 'Strengthen evidence, assurance, and accountability across demanding regulatory environments.'], ['Leadership teams', 'Gain a practical view of key risks, investment decisions, and the status of important controls.'], ['Technology teams', 'Connect security, resilience, privacy, and supplier management into one clearer operating picture.']].map(([a,b]) => <div key={a} className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-semibold">{a}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{b}</p></div>)}</div></div><div className="mt-16 border-t border-slate-200 pt-10"><Eyebrow>Common focus areas</Eyebrow><div className="mt-6 flex flex-wrap gap-3">{['Information security governance', 'Privacy and data governance', 'Third-party risk management', 'Operational resilience', 'Policy management', 'Internal controls', 'Audit preparation', 'Executive risk reporting'].map(x => <span key={x} className="rounded-full border border-[#087fd1]/20 bg-white px-4 py-2.5 text-sm font-medium text-[#000741]">{x}</span>)}</div></div></div></section>
      <section className="mx-auto max-w-7xl px-6 py-24"><div className="rounded-[32px] bg-[#000741] px-7 py-14 text-center text-white sm:px-12"><ShieldCheck className="mx-auto h-8 w-8 text-[#4FA6FF]" /><h2 className="mx-auto mt-6 max-w-2xl text-4xl font-light">Create a GRC program that supports your next move.</h2><p className="mx-auto mt-5 max-w-xl leading-relaxed text-white/65">Start with the risks, obligations, and decisions that matter most to your organization.</p><div className="relative mt-8 inline-block"><span className="absolute inset-0 rounded-xl animate-cta-pulse" style={{ backgroundColor: '#B1B6CE' }} aria-hidden="true" /><button onClick={onHome} className="relative inline-flex min-h-[52px] items-center gap-2 rounded-xl px-8 py-4 text-sm font-semibold shadow-xl transition-all hover:shadow-2xl" style={{ color: '#000741', backgroundColor: '#B1B6CE' }}>Start a conversation <motion.span animate={{ x: [0, 4, 0] }} transition={{ duration: 1.4, repeat: Infinity, ease: 'easeInOut' }} className="inline-flex"><ArrowRight className="h-4 w-4" /></motion.span></button></div></div></section>
    </main>
  </div>;
}

function MicrosoftLayoutPro({ service, onServices, onHome }) {
  const cards = [[LockKeyhole, 'Secure access', 'Identity, device management, and conditional access that protect work without making work harder.'], [UsersRound, 'Connected teams', 'Teams, SharePoint, and Microsoft 365 spaces where information, conversations, and decisions stay together.'], [Workflow, 'Smarter flows', 'Simple approvals, self-service requests, and automation that remove repetitive effort.'], [BarChart3, 'Useful insight', 'Adoption, security, and service signals that show where the workplace can improve next.']];
  const solutions = ['Microsoft 365 strategy', 'Azure foundations', 'Identity and access', 'Defender security', 'Teams and SharePoint', 'Adoption and enablement'];
  return <div className="service-detail-page min-h-screen bg-white text-[#000741]">
    <header className="relative overflow-hidden bg-[#000741] px-6 pb-20 pt-32 text-white lg:pb-28"><div className="absolute inset-0 opacity-30" style={{ backgroundImage: 'radial-gradient(circle at 80% 20%, #087fd1 0, transparent 24%), linear-gradient(rgba(168,220,255,.1) 1px, transparent 1px), linear-gradient(90deg, rgba(168,220,255,.1) 1px, transparent 1px)', backgroundSize: 'auto, 44px 44px, 44px 44px' }} /><div className="relative mx-auto max-w-7xl"><BackButton onClick={onServices} dark />
      <div className="mt-16 grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><motion.div initial={{opacity:0,x:-22}} animate={{opacity:1,x:0}} transition={{duration:.7}}><div className="flex items-center gap-3"><Cloud className="h-5 w-5 text-[#4FA6FF]" /><Eyebrow light>Microsoft and digital workspace</Eyebrow></div><h1 className="mt-7 max-w-2xl text-5xl font-light leading-[1.04] sm:text-6xl">Your best workday starts with a <span className="text-[#4FA6FF]">better workspace.</span></h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-white/65">Bring collaboration, secure access, automation, and insight into a digital experience that feels natural for people and manageable for IT.</p></motion.div><Reveal className="relative overflow-hidden rounded-[30px] bg-white p-3 text-[#000741] shadow-2xl sm:p-4"><div className="rounded-[22px] bg-[#f5f8fc] p-5"><div className="flex items-center justify-between"><div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-[#087fd1]" /><span className="h-2.5 w-2.5 rounded-full bg-[#4FA6FF]" /><span className="h-2.5 w-2.5 rounded-full bg-slate-300" /></div><span className="text-xs font-semibold text-slate-500">My workspace</span></div><div className="mt-6 grid gap-3 sm:grid-cols-[.75fr_1.25fr]"><div className="rounded-2xl bg-[#000741] p-5 text-white"><p className="text-xs text-[#4FA6FF]">Today</p><p className="mt-5 text-xl font-light">Focused, secure, connected.</p><div className="mt-8 rounded-xl bg-white/10 px-3 py-2 text-xs">Identity protected</div></div><div className="space-y-3">{[['Team updates', 'Files and decisions in one place'], ['Approvals', 'Requests moving without delay'], ['Insights', 'A clearer view of work in progress']].map(([a,b]) => <div key={a} className="rounded-xl bg-white p-4 shadow-sm"><p className="font-semibold text-sm">{a}</p><p className="mt-1 text-xs text-slate-500">{b}</p></div>)}</div></div></div></Reveal></div></div>
    </header><main id="workspace-start"><section className="mx-auto max-w-7xl px-6 py-24 lg:py-32"><div className="max-w-3xl"><Eyebrow>More than deployment</Eyebrow><h2 className="mt-5 text-4xl font-light leading-tight">A digital workspace should feel simple for employees and intentional for IT.</h2><p className="mt-6 text-lg leading-relaxed text-slate-600">Our approach joins platform architecture, security, adoption, and governance. You get a workplace shaped around real work patterns rather than a collection of disconnected tools.</p></div><div className="mt-16 grid gap-5 sm:grid-cols-2">{cards.map(([Icon, title, text], i) => <Reveal key={title} delay={i*.07} className="group rounded-2xl border border-slate-200 p-8 transition-all hover:-translate-y-1 hover:border-[#087fd1] hover:shadow-xl"><Icon className="h-6 w-6 text-[#087fd1]" /><h3 className="mt-12 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-relaxed text-slate-600">{text}</p><ArrowUpRight className="mt-7 h-4 w-4 text-[#087fd1]" /></Reveal>)}</div></section>
      <section className="bg-[#000741] px-6 py-24 text-white"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><Eyebrow light>What changes for your people</Eyebrow><h2 className="mt-5 text-4xl font-light">Work becomes easier to find, safer to do, and simpler to complete.</h2></div><div className="grid gap-4 sm:grid-cols-2">{[['For employees', 'A predictable digital experience with less searching, switching, and waiting.'], ['For leaders', 'Clear collaboration patterns and more visible progress across teams.'], ['For IT', 'A governed platform with practical security, support, and lifecycle controls.'], ['For the business', 'A workplace that can flex as priorities, people, and services change.']].map(([a,b]) => <div key={a} className="border-t border-white/20 pt-5"><h3 className="text-lg font-semibold text-[#4FA6FF]">{a}</h3><p className="mt-3 text-sm leading-relaxed text-white/60">{b}</p></div>)}</div></div></div></section>
      <section className="bg-[#f6faff] px-6 py-24"><div className="mx-auto max-w-7xl"><Eyebrow>Where we help</Eyebrow><h2 className="mt-5 text-4xl font-light">A focused improvement or a connected workplace roadmap.</h2><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{solutions.map((x,i) => <Reveal key={x} delay={i*.05} className="rounded-2xl bg-white p-7 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e5f3ff] text-[#087fd1]">{i === 0 ? <Cloud className="h-5 w-5" /> : <Check className="h-5 w-5" />}</span><h3 className="mt-10 font-semibold">{x}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">Tailored to your workforce, systems, security needs, and delivery priorities.</p></Reveal>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-6 py-24"><div className="rounded-[32px] bg-[#087fd1] p-8 text-white sm:p-14"><div className="grid gap-10 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><Eyebrow light>How a rollout feels</Eyebrow><h2 className="mt-5 text-4xl font-light">Clear direction, visible progress, practical support.</h2></div><div className="grid gap-3 sm:grid-cols-2">{['Listen to the workforce', 'Design the secure foundation', 'Launch with enablement', 'Measure and improve'].map(x => <div key={x} className="rounded-xl border border-white/20 bg-white/[.08] p-5 text-sm font-medium">{x}</div>)}</div></div></div><div className="mt-20 text-center"><Cloud className="mx-auto h-8 w-8 text-[#087fd1]" /><h2 className="mx-auto mt-6 max-w-2xl text-4xl font-light">Make your workplace a strategic advantage.</h2><p className="mx-auto mt-5 max-w-lg text-slate-600">Let us map a secure, useful path forward for your Microsoft environment.</p><div className="relative mt-8 inline-block"><span className="absolute inset-0 rounded-xl animate-cta-pulse" style={{ backgroundColor: '#B1B6CE' }} aria-hidden="true" /><button onClick={onHome} className="relative inline-flex min-h-[52px] items-center gap-2 rounded-xl px-8 py-4 text-sm font-semibold shadow-xl transition-all hover:shadow-2xl" style={{ color: '#000741', backgroundColor: '#B1B6CE' }}>Talk to our team <motion.span animate={{ x: [0, 4, 0] }} transition={{ duration: 1.4, repeat: Infinity, ease: 'easeInOut' }} className="inline-flex"><ArrowRight className="h-4 w-4" /></motion.span></button></div></div></section>
    </main>
  </div>;
}

function DigitalTransformationLayoutPro({ service, onServices, onHome }) {
  const moves = [['Find friction', 'Map delays, rework, hidden handoffs, and customer pain points across the work.'], ['Simplify the flow', 'Design future journeys around the decisions, data, and moments that matter.'], ['Build momentum', 'Release practical automation and connected experiences that earn adoption.'], ['Scale what works', 'Use insight and a delivery rhythm to extend value across the organization.']];
  const capabilities = ['Process discovery and mapping', 'Paper to digital workflows', 'Business process automation', 'Systems integration', 'Data and reporting foundations', 'Change and adoption'];
  return <div className="service-detail-page min-h-screen bg-[#050a20] text-white"><header className="relative overflow-hidden px-6 pb-28 pt-32" style={{background:'radial-gradient(circle at 74% 24%,#087fd1 0,transparent 24%),radial-gradient(circle at 24% 88%,#2857b8 0,transparent 30%)'}}><div className="mx-auto max-w-7xl"><BackButton onClick={onServices} dark /><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="mt-16"><div className="flex items-center gap-3"><Workflow className="h-5 w-5 text-[#4FA6FF]" /><Eyebrow light>Digital transformation</Eyebrow></div><h1 className="mt-7 max-w-4xl text-5xl font-light leading-[1.02] sm:text-6xl lg:text-7xl">Build a business that moves with <span className="text-[#4FA6FF]">less friction.</span></h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-white/65">We help you connect people, processes, data, and technology so operational change feels tangible, useful, and ready to scale.</p></motion.div><div className="mt-20 grid gap-3 md:grid-cols-3">{[['Manual work', 'Repeated effort, unclear handoffs, delayed decisions.'], ['Connected flow', 'Guided work, useful automation, and better shared context.'], ['Visible momentum', 'Insight that points to the next most valuable improvement.']].map(([a,b], i) => <div key={a} className={`rounded-2xl p-6 ${i===1 ? 'bg-[#087fd1]' : 'border border-white/15 bg-white/[.06]'}`}><p className="text-lg font-semibold">{a}</p><p className="mt-3 text-sm leading-relaxed text-white/65">{b}</p></div>)}</div></div></header>
    <main id="transform-start"><section className="bg-[#f6f8fc] px-6 py-24 text-[#000741] lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><Eyebrow>The opportunity</Eyebrow><h2 className="mt-5 text-4xl font-light leading-tight">Start with the moments that hold the business back.</h2></div><p className="text-lg leading-relaxed text-slate-600">Transformation succeeds when it starts close to real work. We uncover the delays customers feel, the rework teams carry, and the insight leaders are missing, then focus change where it can make a visible difference.</p></div><div className="mt-16 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{moves.map(([a,b],i) => <Reveal key={a} delay={i*.06} className="rounded-2xl bg-white p-7 shadow-sm"><div className="h-1 w-10 rounded-full bg-[#087fd1]" /><h3 className="mt-10 text-lg font-semibold">{a}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{b}</p></Reveal>)}</div></div></section>
      <section className="px-6 py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><Eyebrow light>Where change takes hold</Eyebrow><h2 className="mt-5 text-4xl font-light">A connected operating model, built around outcomes.</h2></div><p className="max-w-md text-white/60">We combine process design, platform choices, data, and adoption so the improvement holds after the launch.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{capabilities.map((x,i) => <Reveal key={x} delay={i*.05} className="group min-h-56 rounded-2xl border border-white/15 p-7 transition-colors hover:bg-[#087fd1]"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/15 text-[#4FA6FF]"><ArrowUpRight className="h-5 w-5" /></div><h3 className="mt-14 text-lg font-semibold">{x}</h3><p className="mt-3 text-sm leading-relaxed text-white/55 group-hover:text-white/80">Practical improvement connected to a meaningful business outcome.</p></Reveal>)}</div></div></section>
      <section className="bg-[#087fd1] px-6 py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_1fr]"><div><Eyebrow light>What good looks like</Eyebrow><h2 className="mt-5 text-4xl font-light">Less time chasing work. More energy creating value.</h2></div><div className="grid gap-5 sm:grid-cols-2">{[['Clear operational truth','Teams can act on the same current information.'],['Faster decisions','Approvals and exceptions move without unnecessary delay.'],['Better customer journeys','Services feel joined up from the customer perspective.'],['Trusted automation','People understand the flow and know where to step in.']].map(([a,b]) => <div key={a} className="border-t border-white/30 pt-5"><h3 className="text-lg font-semibold">{a}</h3><p className="mt-3 text-sm leading-relaxed text-white/65">{b}</p></div>)}</div></div></section>
      <section className="bg-white px-6 py-24 text-[#000741]"><div className="mx-auto max-w-7xl"><Eyebrow>What you leave with</Eyebrow><h2 className="mt-5 max-w-2xl text-4xl font-light">A delivery rhythm that keeps transformation moving.</h2><div className="mt-14 grid gap-5 md:grid-cols-3">{[['Opportunity map','A prioritized view of friction, value, dependencies, and the best first moves.'],['Working improvements','Connected workflows, useful automation, and the support teams need to adopt them.'],['Improvement backlog','Clear operational signals and a practical plan for what comes next.']].map(([a,b]) => <div key={a} className="rounded-2xl border border-slate-200 p-8"><RefreshCw className="h-5 w-5 text-[#087fd1]" /><h3 className="mt-10 text-xl font-semibold">{a}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{b}</p></div>)}</div><div className="mt-24 rounded-[32px] bg-[#000741] px-7 py-14 text-center text-white sm:px-12"><Network className="mx-auto h-8 w-8 text-[#4FA6FF]" /><h2 className="mx-auto mt-6 max-w-2xl text-4xl font-light">Ready to make work flow better?</h2><p className="mx-auto mt-5 max-w-lg text-white/65">We will help you identify the right first move and build from there.</p><div className="mt-8 inline-block relative"><span className="absolute inset-0 rounded-xl animate-cta-pulse" style={{ backgroundColor: '#B1B6CE' }} aria-hidden="true" /><button onClick={onHome} className="relative inline-flex min-h-[52px] items-center gap-2 rounded-xl px-8 py-4 text-sm font-semibold shadow-xl transition-all hover:shadow-2xl" style={{ color: '#000741', backgroundColor: '#B1B6CE' }}>Plan your next move <motion.span animate={{ x: [0, 4, 0] }} transition={{ duration: 1.4, repeat: Infinity, ease: 'easeInOut' }} className="inline-flex"><ArrowRight className="h-4 w-4" /></motion.span></button></div></div></div></section>
    </main>
  </div>;
}

export { GRCLayoutPro, MicrosoftLayoutPro, DigitalTransformationLayoutPro };
